# Generated by Django 5.0.9 on 2024-11-19 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NhanVien',
            fields=[
                ('MaNhanVien', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('SoDienThoai', models.CharField(max_length=10)),
                ('NgayThangNamSinh', models.DateField()),
                ('NgayBatDauLam', models.DateField()),
                ('HoTen', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=100)),
                ('MaQuanLy', models.CharField(max_length=7)),
            ],
            options={
                'db_table': 'NhanVien',
            },
        ),
    ]
