# Generated by Django 5.0.9 on 2024-11-19 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nhanvien',
            name='SoDienThoai',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
