# Generated by Django 5.0.9 on 2024-11-19 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_nhanvien_sodienthoai'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nhanvien',
            name='MaQuanLy',
            field=models.CharField(max_length=7, null=True),
        ),
    ]
