# Generated by Django 5.0.9 on 2024-11-19 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_nhanvien_maquanly'),
    ]

    operations = [
        migrations.AddField(
            model_name='nhanvien',
            name='DiaChi',
            field=models.CharField(default='Hồ Chí Minh', max_length=255),
        ),
        migrations.AddField(
            model_name='nhanvien',
            name='GioiTinh',
            field=models.CharField(default='nam', max_length=3),
        ),
    ]
